In [44]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
# print(arr,type(arr))
# print(arr.shape)   #shape维度
# arr.shape = (2,3)
# print(arr.shape)

# arr*3    #数组中每一个元素都*3   （跟线性代数规则一致）
# arr+3    #数组中每一个元素都+3   （跟线性代数规则一致）
# arr-3    #数组中每一个元素都-3   （跟线性代数规则一致）
# arr/3    #数组中每一个元素都/3   （跟线性代数规则一致）
# arr[arr>3]
# print(arr + arr)
# s=np.ones(5) /5
# np.zeros_like(s,dtype=np.uint)
# arr = arr.reshape(2,3)
# arr = arr.astype(np.float32)   #修改数据类型：返回一个新数组
# arr.ndim
# print(len(arr))
# arr[:,1]
# arr.shape = (2,3)
# arr
# arr.shape = (3,2)
# arr

# a=np.arange(0,10).reshape(2,5)
# a.dtype = "float32"  #强转类型，数据错误(错误的)
# a.size   #返回元素的个数

# a
# print(len(a))

# arr1 = np.arange(1,19)
# arr1.shape=(3,2,3)
# arr1
# arr1[0,1,0]

# arr.astype(np.str_)
# arr.astype(np.bool_)
#自定义复合数据类型
data=[
    ("zs",[90,80,85],15),
    ("ls",[92,81,83],16),
    ("ww",[95,85,95],15),
]
#第一种设置dtype方式
# a = np.array(data,dtype="U3,3int32,int32")
# a = np.array(data)
# a
#第二种设置dtype方式
# a = np.array(data,dtype=[
#                         #别名,类型 ,占内存字节
#                         ("name","str_",2),
#                         ("scores","int32",3),
#                         ("age","int32",1),
#                          ])
# a
# a["scores"]
# a[2]["age"]

#第三种设置dtype的方式
a=np.array(data,dtype={
    "names":["name","scores","age"],    #别名
    "formats":["U3","3int32","int32"]   #类型名
})
# a[0]["name"]

##第四种设置dtype的方式
a=np.array(data,dtype={
    #别名:(类型,字节偏移量)
    'names':("U3",0),
    'scores':("3int32",16),
    'ages':("int32",28),
})
a
# a.itemsize
#第五种设置dtype的方式
a=np.array([0x1234,0x5667],dtype=(
    "u2",{
        "lowc":("u1",0),
        "hignc":("u1",1),
    }))
a

#日期数据类型
dates=["2021-01-01","2011","2011-02","2011-01-01","2021-01-01 10:10:00"]
a=np.array(dates)


# dates = a.astype("M8[D]")
# # dates = a.astype("M8[s]")
# dates
# print(dates[1] - dates[2])


In [45]:
a=np.arange(12)
a.
#返回新数组，和原数组类似于浅拷贝(当一方数据改变，另一方数据也会跟着改变)
b=a.reshape(3,4)
# b[0,0] =200
# print(a)
# print(b)
# b.ravel()
# b[0,0] =300
# print(a)
# print(b)

##返回新数组，和原数组类似于深拷贝(当一方数据改变，另一方数据不会跟着改变)
# c=b.flatten()
# b[2,3] = 700
# print(b)
# print(c)

#不返回新数组，直接修改原数组
# b.shape=(2,6)
# b
# b.resize((3,4))
# b

In [46]:
#切片
#数组对象[起始位置:终止位置:步长,...]
# arr = np.arange(20).reshape(4,5)
# print(arr)
# arr[0:3:2,0:2:1]

arr = np.arange(20).reshape(2,5,2)
print(arr)
arr[:1,1:,1:3:1]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


array([[[3],
        [5],
        [7],
        [9]]])

In [47]:
# ndarray数组的掩码操作
# a = np.arange(1,10)
# mask = [True,False,True,False,True,False,True,False,True]
# a[mask]  #[1, 3, 5, 7, 9] 通过mask对象选取a数组当中的数据


In [48]:
#基于bool数组的掩码
#输出100以内3的倍数
arr = np.arange(100)
# print(arr[arr % 3 == 0])
print(arr[(arr % 3 == 0) & (arr %7 ==0)])
#基于索引的掩码
name_phone = np.array(["Apple","MI","Mate30 PRO","Oppo","Vivo"])
rank_num = [1,0,3,2,4]
name_phone[rank_num]

[ 0 21 42 63 84]


array(['MI', 'Apple', 'Oppo', 'Mate30 PRO', 'Vivo'], dtype='<U10')

In [2]:
#多维数组的组合和拆分
import numpy as np

a= np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
print(a)
print(b)
#水平方向组合
d=np.hstack((a,b))
print(d,166)

#垂直方向组合（生成新数组）
e=np.vstack((a,b))


#水平方向拆分
k,l=np.hsplit(d,2)
# print(k,l)

#垂直方向拆分(生成两个数组)
# i,j=np.vsplit(e,2)
# print(i,j)
#深度方向操作(三维)
#深度方向组合
s=np.dstack((a,b))
#深度方向拆分
l1,l2=np.dsplit(s,2)
# print(l1,l2)
#多维数组组合与拆分的相关函数
#通过axis作为关键字参数指定组合的方向，取值如下：
#若待组合的数组都是二维数组:
    # 0 :垂直方向组合
    # 1 :水平方向组合
#若待组合的数组都是三维数组:
    # 0 :垂直方向组合
    # 1 :水平方向组合
    # 2 :深度方向组合
np.concatenate((a,b),axis=0)
np.split(d,2,axis=0)

#长度不等的数组组合:
a= np.arange(1,6)
b= np.arange(1,5)
#填充b数组使其长度与a相同
'''
    pad_width:
            0:往头部补0个元素
            1:往尾部补1个元素
'''
b= np.pad(b,pad_width=(0,1),mode="constant",constant_values=-1)
np.vstack((a,b))

#简单的一维数组组合方案
a = np.arange(1,9)
b = np.arange(9,17)
c = np.row_stack((a,b))
print(c,211)
d   = np.column_stack((a,b))
print(d,213)

# np.stack((a,b),axis=1)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] 166
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]] 211
[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]
 [ 8 16]] 213


In [50]:
#ndarray类的其他属性
# shape - 维度
# dtype - 元素类型
# size -  元素数量
# ndim  - 维数 len(shape)
# itemsize - 元素字节数
# nbytes - 总字节数  = size * itemsize
# real - 复数数组的实部数组
# imag - 复数数组的虚部数组
# T - 数组对象的转置视图
# flat - 扁平迭代器
a = np.array([
    [1+1j,2+4j,3+7j],
    [4+2j,5+5j,6+8j],
    [7+3j,8+6j,9+9j],
])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
print(a.itemsize)
print(a.nbytes)
print(a.real)
print(a.imag)
print(a.T)
print(a.flat)





(3, 3)
complex128
9
2
16
144
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
[[1.+1.j 4.+2.j 7.+3.j]
 [2.+4.j 5.+5.j 8.+6.j]
 [3.+7.j 6.+8.j 9.+9.j]]


In [ ]:
"""
    加载文件
    直接读取该文件并且获取ndarray数组对象
    返回值：
        unpack = False              返回一个二维数组
        unpack = False              多个一维数组
    np.loadtxt(fname,delimiter,usecols,unpack,dtype,converters)
        fname                   文件路径
        delimiter               分隔符
        usecols=(1,3)           读取1、3两列，下标从0开始
        unpack                  是否按列拆包
        dtype                   指定返回每一列数组中元素的类型
        converters={1:func}     转换器函数字典

"""
import numpy as np
from datetime import datetime
def dmy2ymd(dmy):
    dmy = str(dmy,encoding="utf-8")
    time = datetime.strptime(dmy,"%d-%m-%Y").date()
    t = time.strftime("%Y-%m-%d")
    return t
dates,opening_prices,highest_prices,lowest_prices,close_prices=np.loadtxt(fname="da_data/aapl.csv",delimiter=",",usecols=(1,3,4,5,6),dtype="M8[D],f8,f8,f8,f8",unpack=True,converters={1:dmy2ymd})
# print(res)
#绘制直线图
from matplotlib import pyplot as plt
from matplotlib import dates as dts
plt.figure("AAPL",facecolor="lightgray")
plt.title("AAPL",fontsize=20)
plt.xlabel("Date",fontsize=14)
plt.ylabel("closing price",fontsize = 14)
plt.grid(linestyle=":")
#拿到坐标轴
ax = plt.gca()
#设置主刻度定位器为周定位器（每周一显示主刻度文本）
ax.xaxis.set_major_locator( dts.WeekdayLocator(byweekday=dts.MO) )
ax.xaxis.set_major_formatter(dts.DateFormatter('%d %b %Y'))
#设置次刻度定位器为日定位器
ax.xaxis.set_minor_locator(dts.DayLocator())
plt.tick_params(labelsize=8)
dates = dates.astype(dts.datetime.datetime)
plt.plot(dates, opening_prices, color='dodgerblue',
		linestyle='-')
plt.gcf().autofmt_xdate()
plt.show()



In [ ]:
"""
    k线图的绘制
"""
import numpy as np
from datetime import datetime
def dmy2ymd(dmy):
    dmy = str(dmy,encoding="utf-8")
    time = datetime.strptime(dmy,"%d-%m-%Y").date()
    t = time.strftime("%Y-%m-%d")
    return t
dates,opening_prices,highest_prices,lowest_prices,close_prices=np.loadtxt(fname="da_data/aapl.csv",delimiter=",",usecols=(1,3,4,5,6),dtype="M8[D],f8,f8,f8,f8",unpack=True,converters={1:dmy2ymd})
# print(res)
#绘制直线图
from matplotlib import pyplot as plt
from matplotlib import dates as dts
plt.figure("AAPL",facecolor="lightgray")
plt.title("AAPL",fontsize=20)
plt.xlabel("Date",fontsize=14)
plt.ylabel("closing price",fontsize = 14)
plt.grid(linestyle=":")
#拿到坐标轴
ax = plt.gca()
#设置主刻度定位器为周定位器（每周一显示主刻度文本）
ax.xaxis.set_major_locator( dts.WeekdayLocator(byweekday=dts.MO) )
ax.xaxis.set_major_formatter(dts.DateFormatter('%d %b %Y'))
#设置次刻度定位器为日定位器
ax.xaxis.set_minor_locator(dts.DayLocator())
plt.tick_params(labelsize=8)
dates = dates.astype(dts.datetime.datetime)
plt.plot(dates, opening_prices, color='dodgerblue',
		linestyle='--',linewidth=2,alpha=0.3)
#整理颜色
rise = close_prices > opening_prices
# 第一种方法
# color = ["red" if c else "green" for c in rise]
# print(color)
# 第二种利用掩码
color = np.zeros(rise.size,dtype="U5")
color[:] = "green"
color[rise] = "white"


edgecolor = ["red" if c else "green" for c in rise]
#绘制实体
# plt.bar(dates,close_prices-opening_prices,color=color,linewidth=0.8,bottom=opening_prices,edgecolor="black",zorder=3)
plt.bar(dates,close_prices-opening_prices,linewidth=0.8,color=color,bottom=opening_prices,edgecolor=edgecolor,zorder=3)
#绘制影线
plt.vlines(dates,ymin=lowest_prices,ymax=highest_prices,color=edgecolor)

plt.legend()
plt.gcf().autofmt_xdate()
plt.show()


